name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Skipping npm install if you already have a built version
      # You can uncomment this if you still need to run npm install and force install
      # - name: Install dependencies
      #   run: npm install --legacy-peer-deps

      # Skip npm run build if your build already exists, or keep it if it's needed.
      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITNESS_APP_C5282 }}
          projectId: fitness-app-c5282
